### ISSUE TITLE
Pyfits is deprecated

### ISSUE THREAD

**Issue by saimn** [kasperschmidt/TDOSE#1]
Hi Kasper,

I see that you are [using](https://github.com/kasperschmidt/TDOSE/search?q=pyfits&unscoped_q=pyfits) PyFITS, however it is deprecated and no longer supported (https://github.com/spacetelescope/pyfits). 
Astropy `io.fits` should be used instead, and should be entirely compatible. I see that you are sometimes using both, is there a reason for this?

**Comment by kasperschmidt** [comment]
Hi Simon
Thanks for pointing this out. 
I'm aware that PyFITS is no longer supported. 
I just didn't get around to replace it by Astropy's io.fits everywhere yet.
The reason I'm currently using both PyFITS and astropy.io.fits is mostly due to sloppiness on my side using old code written with PyFITS when building TDOSE - sorry.
I'll leave the issue open as a reminder to get this done.

**Comment by saimn** [comment]
Hi Kasper,
Ok thanks. I wanted to give a try to TDOSE, to compare with our deblending code, but I did not have the time yet. If I manage to do this soon enough I will make the change and propose of PR.

**Comment by thriveth** [comment]
Wouldn't a simple "import astropy.io.fits as pyfits" solve like 90% of the problem?

**Comment by kasperschmidt** [comment]
Thanks for the reminder to take a look at this @thriveth - and yes you are probably right, that just swapping pyfits for astropy.io.fits would fix most of the cases. But often the last few % is what takes most of the work. But I'll bump the issue up my todo list.

**Comment by kasperschmidt** [comment]
Thanks for the reminder to take a look at this @thriveth - and yes you are probably right, that just swapping pyfits for astropy.io.fits would fix most of the cases. But often the last few % is what takes most of the work. But I'll bump the issue up my todo list.

**Comment by kasperschmidt** [comment]
Thanks for the reminder to take a look at this @thriveth - and yes you are probably right, that just swapping pyfits for astropy.io.fits would fix most of the cases. But often the last few % is what takes most of the work. But I'll bump the issue up my todo list.

**Comment by kasperschmidt** [comment]
Thanks for the reminder to take a look at this @thriveth - and yes you are probably right, that just swapping pyfits for astropy.io.fits would fix most of the cases. But often the last few % is what takes most of the work. But I'll bump the issue up my todo list.

**Comment by thriveth** [comment]
@kasperschmidt It's probably easier said than done but do you have a set of stanbdard tests to run on your code? That way it would be easier for others to contribute to the code and for you to check whether a pull request holds up (yes I am contemplating using your code for a project at the moment).

**Comment by kasperschmidt** [comment]
I did put together some test data that can be used to check TDOSE. Will try to get those in a "public version" asap.

**Comment by kasperschmidt** [comment]
Alright, so pyfits should be gone. Will open a new issue to remind myself to update and publish the example scripts and data as you suggested @thriveth

**Comment by thriveth** [comment]
Out of curiosity, was anything else than updated import statements necessary?

**Comment by kasperschmidt** [comment]
Apart from just changing from pyfits to astropy.io.fits (and handling the depreciation of clobber) the pyfits.new_table() function does not exist under astropy. Hence this had to be updated to astropy.io.fits.BinTableHDU.from_columns(). But generally and easy update.
