### ISSUE TITLE
A couple of questions about documentation

### ISSUE THREAD

**Issue by thriveth** [kasperschmidt/TDOSE#5]
Hi, 

I am currently attempting to run some cubes and catalogs with TDOSE, but am getting a little stuck so I have a couple of questions about how to read/interpret the documentation in the appendices of Schmidt+ 2019. 

1. Running in `gauss` modeling mode, the setup file asks for a "flux scale" column in the input catalog. Is this simply the photometric aperture sum in the model image, to give a sane first-guess to the Gauss fitting algorithm? 
2. I am a little in doubt about what format or formats the PSF should be given in.  More specifically, I want to use an HST image as the model image, but obviously the PSFs of that and the MUSE observations are quite different. Should it simply be the seeing of the MUSE observations, a corrective Gaussian, or something else?  Should it be in the form of a numerical array like in Source Extractor, or a sigma value, assuming a Gaussian, or something else?
3. More about strategy: If I have a semi-crowded field, and want to extract a galaxy in close vicinity - do I simply set a small size to the cutouts for that galaxy, or are there other options I have missed in reading the paper?

**Comment by kasperschmidt** [comment]
1. The flux scale for the Gaussian modeling is indeed used for the initial guess when producing the reference image model (if no guess is provided explicitly). It's an attempt to prevent the scipy optimizer curve_fit from wandering off and getting stuck somewhere. What's important is the approximate relative fluxes of the sources. But for testing purposes there is nothing problematic about just setting this to a fixed value for all sources and let the optimizer to the job.

2. You should not provide a PSF for the reference image modeling. Whenever TDOSE talks about PSF, it's for the spectral data cube. This information is provided as Gaussian parameters as a linear function of wavelength in the setup file. That's the PSF the reference image model will be convolved with. For constructing the reference image model, TDOSE just takes whatever image is provided "as is".

3. Here the "de-blending" capabilities of TDOSE will be of importance. If you just use a small cutout, TDOSE has no way of accounting for the contaminating flux from the neighboring source(s). If you on the other hand generate a reference image model that includes the contaminant(s) the(ir) flux can be "de-blended" from the object of interest in the extraction process. The succes of this de-blending will then depend on the quality of the reference image model (and how well that represents the contaminating light that needs to be accounted for). Such de-blending is described in section 4.4 and examples given in Figures 6 and 7 of Schmidt et al. (2019).

**Comment by thriveth** [comment]
Thanks for your quick and thorough replies, @kasperschmidt !

**Comment by kasperschmidt** [comment]
Velbekomme :)
I'll close this then.
